//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIA_Flight_Booking_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking_Detail()
        {
            this.Seat_Detail = new HashSet<Seat_Detail>();
        }
    
        public System.Guid BookingID { get; set; }
        public System.Guid FlightID { get; set; }
        public System.Guid BookedByCustomerID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> BookingDateTime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Flight_Detail Flight_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seat_Detail> Seat_Detail { get; set; }
    }
}
