//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIA_Flight_Booking_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetails_VM
    {
        public System.Guid BookingID { get; set; }
        public Nullable<System.Guid> FlightID { get; set; }
        public Nullable<System.TimeSpan> Departure_Time { get; set; }
        public Nullable<System.DateTime> Departure_Date { get; set; }
        public string DepartureVenue { get; set; }
        public string DestinationVenue { get; set; }
        public Nullable<int> SeatID { get; set; }
        public System.Guid TicketID { get; set; }
        public string Name { get; set; }
    }
}
