//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIA_Flight_Booking_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight_Detail()
        {
            this.Pricings = new HashSet<Pricing>();
            this.Booking_Detail = new HashSet<Booking_Detail>();
        }
    
        public System.Guid FlightID { get; set; }
        public System.Guid AircraftID { get; set; }
        public string DepartureVenue { get; set; }
        public string DestinationVenue { get; set; }
        public System.DateTime DepartureDateTime { get; set; }
        public System.DateTime ArrivalDateTime { get; set; }
    
        public virtual Aircraft_Detail Aircraft_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pricing> Pricings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_Detail> Booking_Detail { get; set; }
    }
}
