//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIA_Flight_Booking_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UIAEntities : DbContext
    {
        public UIAEntities()
            : base("name=UIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Passenger> Passengers { get; set; }
        public virtual DbSet<Seat_Detail> Seat_Detail { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Aircraft_Detail> Aircraft_Detail { get; set; }
        public virtual DbSet<Flight_Detail> Flight_Detail { get; set; }
        public virtual DbSet<Pricing> Pricings { get; set; }
        public virtual DbSet<Booking_Detail> Booking_Detail { get; set; }
        public virtual DbSet<BookingList_VM> BookingList_VM { get; set; }
        public virtual DbSet<BookingDetails_VM> BookingDetails_VM { get; set; }
    
        public virtual int SP_SeatDetails_Insert(Nullable<System.Guid> bookingID, Nullable<int> seatID)
        {
            var bookingIDParameter = bookingID.HasValue ?
                new ObjectParameter("BookingID", bookingID) :
                new ObjectParameter("BookingID", typeof(System.Guid));
    
            var seatIDParameter = seatID.HasValue ?
                new ObjectParameter("SeatID", seatID) :
                new ObjectParameter("SeatID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SeatDetails_Insert", bookingIDParameter, seatIDParameter);
        }
    }
}
